#!/bin/bash
#SBATCH --job-name=t3opt
#SBATCH --partition=ceres
#SBATCH --nodes=1                    # ONE node: every worker shares one SQLite store
#SBATCH --ntasks=32
#SBATCH --mem=1800G                  # ~22 workers x 82 GB measured worst case
#SBATCH --time=21-00:00:00           # 3 weeks, the ceres maximum; submit.local.sh overrides it
                                     # and is the single place the wall clock is declared.
                                     # The job is EXPECTED to be killed here -- there is no
                                     # matching max_hours, deliberately.
#SBATCH --account=CHANGEME
# Relative, so they follow the submitting directory -- a fallback only. submit.local.sh passes
# absolute paths under $OPTIMIZER_HOME/logs on the command line, which override these.
#SBATCH --output=logs/slurm-%j.out
#SBATCH --error=logs/slurm-%j.err
#
# Optimizer on SciNet Ceres, inside the Apptainer image. See RUNBOOK_SLURM.md §7.
#
# DO NOT EDIT THIS FILE to set your account, paths or sizing. It is tracked in git, so local
# edits conflict on every `git pull`. Those values belong in submit.local.sh, which is
# gitignored -- copy submit.local.sh.example once and edit that:
#
#   cp submit.local.sh.example submit.local.sh && chmod +x submit.local.sh
#   ./submit.local.sh
#
# The #SBATCH directives below are DEFAULTS. sbatch command-line flags override them, which is
# how submit.local.sh supplies the real values without touching this file.
#
# CHAIN IT for runs longer than 3 weeks -- the store is resumable, so only the evaluations
# in flight at the cutoff are lost (median 29 min each):
#
#   jid=$(./submit.local.sh --parsable)
#   ./submit.local.sh --dependency=afterany:$jid
#
# BEFORE THE FIRST REAL SUBMISSION, do a 30-minute shakeout:
#   ./submit.local.sh --qos=debug --time=00:30:00 --ntasks=4 --mem=200G
# Two workers for half an hour costs nothing and catches every path and credential mistake.

set -euo pipefail

# ---- paths: supplied, never invented --------------------------------------
# These arrive from submit.local.sh via `sbatch --export=ALL`. REQUIRED rather than defaulted:
# submit.local.sh reads OPTIMIZER_HOME from .Renviron, which is the single source, and a
# default here could silently contradict it. Fail instead.
: "${OPTIMIZER_HOME:?not set -- submit through container/submit.local.sh, which reads it from .Renviron}"
: "${REPO:?not set -- submit through container/submit.local.sh}"
export OPTIMIZER_HOME
# Beside the recipe, matching build.sh and run_in_container.sh -- not in OPTIMIZER_HOME, which
# is for state that cannot be regenerated.
SIF="${SIF:-$REPO/container/optimizer.sif}"

# apptainer is NOT on PATH by default on Ceres; it needs `module load apptainer`, and a batch
# shell may not even have the `module` function defined. Do this BEFORE anything expensive:
# a job that queues for days and then dies on "command not found" wastes the slot, not just
# the run. See container/lib_apptainer.sh.
. "$REPO/container/lib_apptainer.sh"
ensure_apptainer || exit 1

# The live store goes on node-local disk. SQLite's WAL coordinates through an mmap'd -shm file
# that network filesystems do not provide; settings.local.R puts db_path under $TMPDIR, which
# on a Ceres compute node is the 1.5 TB local NVMe (mounted at /tmp, whatever the docs say).
#
# Unset TMPDIR, or no SLURM_JOB_ID, means we are not inside a job -- and then $TMPDIR is shared
# storage, which is the one configuration that corrupts the store.
: "${TMPDIR:?TMPDIR is unset -- not inside a SLURM job? The store MUST be on node-local disk}"
: "${SLURM_JOB_ID:?SLURM_JOB_ID is unset -- this must run as a SLURM job, not on a login node}"

# Workers x threads <= ntasks. Memory, not cores, is the binding constraint: raise the
# worker count only after report_memory.R confirms headroom.
N_WORKERS="${N_WORKERS:-22}"
N_THREADS="${N_THREADS:-1}"

mkdir -p "$OPTIMIZER_HOME/state" "$OPTIMIZER_HOME/logs"

# ---- restore the store into node-local scratch ---------------------------
# The optimizer does NOT restore the store by itself -- restore_cache_from_backup() covers the
# cache, but there is no equivalent for evals.sqlite. Without this copy a chained job starts
# from an empty store and re-runs work already paid for.
#
# This must match db_path in settings.local.R (from container/settings.local.R.scinet).
# Both are "$TMPDIR/t3opt_<user>/evals.sqlite" -- deliberately simple, so the two agree by
# inspection. If you change one, change the other: a mismatch restores the backup to a path
# nobody reads, and the run starts empty without complaining.
BACKUP="$OPTIMIZER_HOME/state/evals_backup.sqlite"
STORE="$TMPDIR/t3opt_$(id -un)/evals.sqlite"
mkdir -p "$(dirname "$STORE")"
echo "store     : $STORE"

if [ -f "$BACKUP" ]; then
  cp "$BACKUP" "$STORE"
  # VACUUM INTO emits a self-contained file with no -wal sidecar, so the copy is complete as
  # it stands. Report what came back, so a silently-empty restore cannot pass unnoticed.
  echo "restored $(sqlite3 "$STORE" 'SELECT COUNT(*) FROM evals;' 2>/dev/null || echo '?') rows from $BACKUP"
else
  echo "no backup at $BACKUP -- starting from an EMPTY store"
  echo "  (expected only on the very first job; check this if you meant to resume)"
fi

echo "node      : $(hostname)"
echo "TMPDIR    : $TMPDIR"
echo "home      : $OPTIMIZER_HOME"
echo "image     : $SIF"
echo "workers   : $N_WORKERS x $N_THREADS threads"
apptainer inspect "$SIF" 2>/dev/null | grep -iE "optimizer.build|r.version|sha" || true

# The cd into $REPO is load-bearing: R reads .Renviron -- and therefore the T3 credentials
# -- from the working directory only. Apptainer 1.1+ does not bind $PWD, hence the explicit
# binds, each mapping a path onto itself so the paths settings.R computes stay valid.
apptainer exec \
  --bind "$REPO:$REPO" \
  --bind "$OPTIMIZER_HOME:$OPTIMIZER_HOME" \
  --bind "$TMPDIR:$TMPDIR" \
  "$SIF" \
  bash -c "cd '$REPO' && ./run_workers.sh $N_WORKERS $N_THREADS"

# run_workers.sh ends in `wait`, so this returns only when every worker has stopped. On
# timeout SLURM kills the job; the next chained job resumes from the backed-up store.
